### ISSUE TITLE
Can't find a way to control `BinaryTree()` aspect ratio

### ISSUE THREAD

**Issue by dimitryzub** [billtrn/dsplot#3]
Is there a way to apply `height` and `width` i.e aspect ratio? I saw that there's an [`unflatten()` method](https://github.com/pygraphviz/pygraphviz/blob/0d3baf27119a4265f7fdf661ca1366e7bdeda4ba/pygraphviz/agraph.py#L1410) but not quite sure how to use it with `BinaryTree()`. Does `unflatten()` created for such a task?

If `BinaryTree()`  has a lot of nodes, the image draws either wide or tall depending on what orientation is applied (`'TB'` or `'LR'`).

<details>
<summary>Drawn image with long height and small width</summary>

![tree](https://user-images.githubusercontent.com/78694043/202841473-0027d9d2-9cec-4e69-ac91-69e1d7f85680.png)
</details>

Code snippet I've used:

```python
from serpapi import GoogleSearch
from urllib.parse import urlsplit, parse_qsl
from dsplot.tree import BinaryTree

def main():
    params = {
        'api_key': '<serpapi_key>',
        'device': 'desktop',
        'engine': 'google',
        'q': 'cats',
        'gl': 'us',
        'hl': 'en'
    }

    search = GoogleSearch(params)

    nodes = []
    
    # pagination
    while True:
        results = search.get_dict()
        
        for related_search in results['related_searches']:
            nodes.append(related_search['query'])
            
        if 'next' in results.get('serpapi_pagination', {}):
            search.params_dict.update(dict(parse_qsl(urlsplit(results.get('serpapi_pagination').get('next')).query)))
        else: 
            break
            
    tree = BinaryTree(nodes=nodes)
    tree.plot(orientation='LR', shape='circle')
    
if __name__ == '__main__':
    main()
```

<details>
<summary>Output image</summary>

![_tree](https://user-images.githubusercontent.com/78694043/205009369-38b97156-7814-464b-890e-2ddd1ce35258.png)

</details>

Thank you 🙂

**Comment by ducttrn** [comment]
Thank you for raising this issue! I will look into that method and see if I could support it soon!

**Comment by ducttrn** [comment]
Hi Dimitry! As I understand, you want to use the `unflatten` method to improve layout for graph that is too tall/wide, is that correct? Can you paste here the code you used to generate the graph in your description (the one with cats)? And also please let me know what you expect the `unflatten` to do for such a long graph? Just asking so that I can find a proper way to bridge between `graphviz` and `dsplot`. Thanks!

**Comment by dimitryzub** [comment]
Hi @billtrn, thank you for your response 🙂 Sorry for the long reply.

> As I understand, you want to use the unflatten method to improve layout for graph that is too tall/wide, is that correct? 

It is correct 👍 However, I'm not 100% if `unflatten` is designed to do that.

>  Can you paste here the code you used to generate the graph in your description (the one with cats)?

Sure, I've updated the initial issue comment.

> also please let me know what you expect the unflatten to do for such a long graph? 

Thank you for this question 🙂  

Based on my current train of thought I expect if the image `height` becomes bigger and bigger, the `width` should become bigger also to compensate for height to make the graph more readable (if a lot of nodes are present).

Not sure how to articulate this better right now, however, I expect something like this:

![image](https://user-images.githubusercontent.com/78694043/205011298-f488c5d9-7bb9-4009-9aca-ae25319c69b5.png)

Hope it helps. Let me know what else I can do to help you 🙂

**Comment by ducttrn** [comment]
Thank you for your thoughtful response, @dimitryzub! Upon looking into the [documentation](https://graphviz.org/docs/cli/unflatten/) of `graphviz`, I think `unflatten` is not intended for our case, and indeed it is only for directed graph.

I have found a solution that allows users to manually put in the `height : width` ratio for the output graph. I tried it on your input graph and get the following result with the ratio of `1.2`:
![tree](https://user-images.githubusercontent.com/56772265/205119611-10333bbc-1d32-46f4-b5a6-df41e755c4ec.png)
Here I used a ratio of `1.2`, but you can feed in any numeric ratio you want! This gives users the flexibility to resize the output image to fit their cases.

If this sounds good for you and your case, let me know and I will publish a new version with this new feature!

P/S: your team's API is so interesting and easy to use! The onboarding process is also really smooth!

**Comment by dimitryzub** [comment]
@billtrn thank you so much for your response 🙂 This is awesome✨

>  I think unflatten is not intended for our case, and indeed it is only for directed graph.

Makes sense 👍

> I have found a solution that allows users to manually put in the height : width ratio for the output graph.

👍👍👍
Is it possible to somehow increase circles scale? They're so tiny 🤏🙂

Or `height : width` dictates their scale?

> If this sounds good for you and your case, let me know and I will publish a new version with this new feature!

Sounds great. The only thing I'm currently concerned about is the circles scale.

> P/S: your team's API is so interesting and easy to use! The onboarding process is also really smooth!

Thank you so much 💛 I'll let our team know about it.
